# Generated by Django 5.2.1 on 2025-06-03 08:53

import django.db.models.deletion
from django.db import migrations, models

import credit_charge.model_validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=16,
                        unique=True,
                        validators=[credit_charge.model_validators.validate_phone_number],
                        verbose_name="شماره موبایل",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=0, default=0, help_text="تومان", max_digits=12, verbose_name="بالانس حساب کاربر"
                    ),
                ),
                ("is_seller", models.BooleanField(default=False, verbose_name="فروشنده")),
            ],
            options={
                "verbose_name": "کاربر",
                "verbose_name_plural": "کاربران",
            },
        ),
        migrations.CreateModel(
            name="Charge",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("WAITING", "در انتظار تأیید"), ("CONFIRMED", "تأیید شده"), ("FAILED", "رد شده")],
                        default="WAITING",
                        max_length=16,
                        verbose_name="وضعیت تراکنش",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, help_text="تومان", max_digits=12, verbose_name="مقدار شارژ حساب"
                    ),
                ),
                ("transaction_id", models.UUIDField(unique=True, verbose_name="شناسه شارژ")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="credit_charge.user",
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "شارژ حساب",
                "verbose_name_plural": "شارژ حساب\u200cها",
            },
        ),
        migrations.CreateModel(
            name="UserTransaction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("transaction_id", models.UUIDField(unique=True, verbose_name="کد پیگیری")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0, help_text="تومان", max_digits=12, verbose_name="مقدار شارژ حساب"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("WAITING", "در انتظار تأیید"), ("CONFIRMED", "تأیید شده"), ("FAILED", "رد شده")],
                        default="WAITING",
                        max_length=16,
                        verbose_name="وضعیت تراکنش",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        choices=[("INSUFFICIENT_BALANCE", "Insufficient Balance"), ("OTHER_REASONS", "Other Reasons")],
                        max_length=32,
                        null=True,
                        verbose_name="توضیحات",
                    ),
                ),
                (
                    "receiver_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receiver_payments",
                        to="credit_charge.user",
                        verbose_name="کاربر دریافت کننده",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sender_payments",
                        to="credit_charge.user",
                        verbose_name="فروشنده",
                    ),
                ),
            ],
            options={
                "verbose_name": "تراکنش بین کاربران",
                "verbose_name_plural": "تراکنش\u200cهای بین کاربران",
            },
        ),
    ]
